### ISSUE TITLE
Import to Forestry Link Error + Correction

### ISSUE THREAD

**Issue by owlsecco** [gethugothemes/omega-hugo#1]
Hi, kindly remove the / in https://app.forestry.io/quick-start?repo=gethugothemes/omega-hugo/&engine=hugo&version=0.60.1&config=exampleSite

Otherwise it will fail looking for gethugothemes/omega-hugo/.git

Modified version: https://app.forestry.io/quick-start?repo=gethugothemes/omega-hugo&engine=hugo&version=0.60.1&config=exampleSite

**Comment by somratpro** [comment]
Hey @owlsecco 
 Thanks for your concern, I fixed it. now you can simply import this to forestry.
